const SINGLE_TOUCH_START_EVENT = "TOUCH_START";
const SINGLE_TOUCH_MOVE_EVENT = "TOUCH_MOVE";
const SINGLE_TOUCH_END_EVENT = "TOUCH_END";

const DOUBLE_TOUCH_START_EVENT = "DOUBLE_TOUCH_START";
const DOUBLE_TOUCH_END_EVENT = "DOUBLE_TOUCH_END";

const TOUCH_EVENT_TIMEOUT = 200;

const THEME_ID = 1;

const PULSE_ME_LIKE_YOU_OWN_ME = 10;
